# Generated by Django 5.2.17 on 2026-09-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('source_id', models.CharField(max_length=64)),
                ('url', models.URLField(blank=True, max_length=400)),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'source_id'), name='uniq_raw_listing')],
            },
        ),
    ]
