# Generated by Django 5.2.17 on 2026-09-28 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=40)),
                ('make_fa', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('model_fa', models.CharField(max_length=40)),
                ('trim', models.CharField(blank=True, max_length=60)),
                ('trim_fa', models.CharField(blank=True, max_length=60)),
                ('year_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('body_type', models.CharField(choices=[('sedan', 'سدان'), ('hatchback', 'هاچبک'), ('crossover', 'کراس\u200cاوور'), ('suv', 'شاسی\u200cبلند'), ('pickup', 'وانت'), ('other', 'سایر')], default='other', max_length=12)),
                ('engine_cc', models.PositiveIntegerField(blank=True, null=True)),
                ('gearbox', models.CharField(blank=True, choices=[('manual', 'دستی'), ('automatic', 'اتوماتیک')], max_length=10)),
                ('fuel_type', models.CharField(choices=[('gasoline', 'بنزینی'), ('dual', 'دوگانه\u200cسوز'), ('other', 'سایر')], default='gasoline', max_length=10)),
                ('fuel_consumption', models.FloatField(blank=True, help_text='Combined, litres/100km', null=True)),
                ('airbags', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('abs', models.BooleanField(null=True)),
                ('esc', models.BooleanField(null=True)),
            ],
            options={
                'ordering': ['make', 'model', 'trim'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('raw_name', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('seed', 'Seed'), ('exact', 'Exact'), ('llm', 'Llm'), ('manual', 'Manual')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.vehicle')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'raw_name'), name='uniq_alias')],
            },
        ),
    ]
