# Generated by Django 5.2.17 on 2026-09-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='family',
            field=models.CharField(default='', help_text='Groups trims for market stats, e.g. peugeot-206ir or quick', max_length=60),
        ),
    ]
