# Generated by Django 5.2.17 on 2026-09-28 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelStats',
            fields=[
                ('model_key', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('offer_count', models.PositiveIntegerField(default=0)),
                ('popularity', models.FloatField(default=0, help_text='Percentile 0-1 among in-scope models')),
                ('depreciation', models.FloatField(blank=True, help_text='Average share of price lost per year', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('year', models.PositiveSmallIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('price', models.BigIntegerField(help_text='Toman; lowest among its Listings')),
                ('gearbox', models.CharField(blank=True, choices=[('manual', 'دستی'), ('automatic', 'اتوماتیک')], max_length=10)),
                ('fuel_type', models.CharField(blank=True, choices=[('gasoline', 'بنزینی'), ('dual', 'دوگانه\u200cسوز'), ('other', 'سایر')], max_length=10)),
                ('body_condition', models.CharField(blank=True, choices=[('clean', 'بدون رنگ'), ('minor', 'رنگ جزئی'), ('major', 'رنگ زیاد / تصادفی')], max_length=6)),
                ('exclusion', models.CharField(blank=True, choices=[('instalment', 'قسطی / لیزینگی'), ('presale', 'حواله / پیش\u200cفروش'), ('placeholder', 'قیمت نامعتبر')], max_length=12)),
                ('city', models.CharField(default='tehran', max_length=40)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=400)),
                ('fair_price', models.BigIntegerField(blank=True, null=True)),
                ('p_cheaper', models.FloatField(blank=True, help_text='Share of comparables priced higher', null=True)),
                ('verdict', models.CharField(choices=[('great', 'زیر قیمت'), ('fair', 'منصفانه'), ('overpriced', 'گران'), ('suspicious', 'مشکوک'), ('unknown', 'داده کافی نیست')], default='unknown', max_length=12)),
                ('confidence', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=6)),
                ('comparable_ids', models.JSONField(blank=True, default=list)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='catalog.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('source_id', models.CharField(max_length=64)),
                ('url', models.URLField(blank=True, max_length=400)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('raw_name', models.CharField(blank=True, max_length=200)),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='Solar model year, e.g. 1399', null=True)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.BigIntegerField(blank=True, help_text='Toman', null=True)),
                ('gearbox', models.CharField(blank=True, choices=[('manual', 'دستی'), ('automatic', 'اتوماتیک')], max_length=10)),
                ('fuel_type', models.CharField(blank=True, choices=[('gasoline', 'بنزینی'), ('dual', 'دوگانه\u200cسوز'), ('other', 'سایر')], max_length=10)),
                ('body_condition', models.CharField(blank=True, choices=[('clean', 'بدون رنگ'), ('minor', 'رنگ جزئی'), ('major', 'رنگ زیاد / تصادفی')], max_length=6)),
                ('body_condition_raw', models.CharField(blank=True, max_length=200)),
                ('exclusion', models.CharField(blank=True, choices=[('instalment', 'قسطی / لیزینگی'), ('presale', 'حواله / پیش\u200cفروش'), ('placeholder', 'قیمت نامعتبر')], max_length=12)),
                ('city', models.CharField(default='tehran', max_length=40)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=400)),
                ('raw', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingest.rawlisting')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.vehicle')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='market.offer')),
            ],
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['price'], name='market_offe_price_fffb4c_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['vehicle', 'year'], name='market_offe_vehicle_450ef1_idx'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('source', 'source_id'), name='uniq_listing'),
        ),
    ]
