# Generated by Django 5.2.17 on 2026-09-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCache',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=60)),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
